#!/bin/bash

WALLPAPER=~/Pictures/Wallpapers/EmiliaVector.png

while true; do
	sleep 1s
	BATLVL=$(upower -i /org/freedesktop/UPower/devices/battery_BAT1 |\
		grep -oE "[0-9]*%" |\
		grep -oP "\d*" |\
		head -1)
        CHARGING=$(upower -i /org/freedesktop/UPower/devices/battery_BAT1 |\
		grep "state: *charging")
	
	export BATLVL
	BATLVL=$(perl -e 'print 10*sqrt($ENV{BATLVL})')

	if [ ${#CHARGING} -gt 0 ]; then
		feh --bg-fill $WALLPAPER
	else
		convert $WALLPAPER \
		-set option:modulate:colorspace hsb \
		-modulate $BATLVL ~/.wallpaper.png

		feh --bg-fill ~/.wallpaper.png
	fi
done
	
