#!/bin/bash

while true; do
	BATLVL=$(upower -i /org/freedesktop/UPower/devices/battery_BAT1 |\
		grep -oE "[0-9]*%" |\
		grep -oP "\d*" |\
		head -1)
	
	if [ $BATLVL -gt 30 ]; then
		feh --bg-fill ~/Pictures/Wallpapers/EmiliaVector.png
	elif [ $BATLVL -gt 15 ]; then
		feh --bg-fill ~/Pictures/Wallpapers/KillLaKillSatsuki.jpg
	else
		feh --bg-fill ~/Pictures/Wallpapers/KillLaKillMatoi2.png
	fi

	sleep 1m
done
	
